# **Music Recommendation System**

# **Mounting Google Drive**

In [6]:
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Dataset**

In [7]:
TRAIN_PATH = "/content/drive/MyDrive/SpotifyDataset/TrainData"
TEST_PATH = "/content/drive/MyDrive/SpotifyDataset/TestData"

# **Importing Libraries** **bold text**

In [8]:
import numpy as np
#Pandas is one of the tools in Machine Learning which is used for data cleaning and analysis. It has features which are used for exploring, cleaning, transforming and visualizing from data.
import pandas as pd
#creating a NumPy array and calculating its mean using the “np” shorthand for concise code.
import numpy as np
#Seaborn is a library that uses Matplotlib underneath to plot graphs. It will be used to visualize random distributions.
import seaborn as sns
#*os* and *os.path* modules include many functions to interact with the file system.
import os

# **Data Preprocessing**

In [9]:
# make sure the file is already there
print(os.listdir(TRAIN_PATH))

['data.csv', 'data_by_artist.csv', 'data_by_year.csv', 'data_w_genres.csv', 'data_by_genres.csv', 'ex.csv']


In [10]:
#To access data from the CSV file, we require a function read_csv() from Pandas that retrieves data in the form of the data frame.
df =pd.read_csv("/content/drive/MyDrive/SpotifyDataset/TrainData/data.csv")
#(show the dataset)df is a variable that holds the reference file to the pandas DataFrame
df

valence  year  acousticness  \
0        0.0594  1921       0.98200   
1        0.9630  1921       0.73200   
2        0.0394  1921       0.96100   
3        0.1650  1921       0.96700   
4        0.2530  1921       0.95700   
...         ...   ...           ...   
170648   0.6080  2020       0.08460   
170649   0.7340  2020       0.20600   
170650   0.6370  2020       0.10100   
170651   0.1950  2020       0.00998   
170652   0.6420  2020       0.13200   

                                                  artists  danceability  \
0       ['Sergei Rachmaninoff', 'James Levine', 'Berli...         0.279   
1                                          ['Dennis Day']         0.819   
2       ['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...         0.328   
3                                        ['Frank Parker']         0.275   
4                                          ['Phil Regan']         0.418   
...                                                   ...           ...   
170648  ['Anuel AA', 'Daddy Yankee', 'KAROL G', 'Ozuna...         0.786   
170649                                       ['Ashnikko']         0.717   
170650                                        ['MAMAMOO']         0.634   
170651                                         ['Eminem']         0.671   
170652                              ['KEVVO', 'J Balvin']         0.856   

        duration_ms  energy  explicit                      id  \
0            831667   0.211         0  4BJqT0PrAfrxzMOxytFOIz   
1            180533   0.341         0  7xPhfUan2yNtyFG0cUWkt8   
2            500062   0.166         0  1o6I8BglA6ylDMrIELygv1   
3            210000   0.309         0  3ftBPsC5vPBKxYSee08FDH   
4            166693   0.193         0  4d6HGyGT8e121BsdKmw9v6   
...             ...     ...       ...                     ...   
170648       301714   0.808         0  0KkIkfsLEJbrcIhYsCL7L5   
170649       150654   0.753         0  0OStKKAuXlxA0fMH54Qs6E   
170650       211280   0.858         0  4BZXVFYCb76Q0Klojq4piV   
170651       337147   0.623         1  5SiZJoLXp3WOl3J4C8IK0d   
170652       189507   0.721         1  7HmnJHfs0BkFzX4x8j0hkl   

        instrumentalness  key  liveness  loudness  mode  \
0               0.878000   10    0.6650   -20.096     1   
1               0.000000    7    0.1600   -12.441     1   
2               0.913000    3    0.1010   -14.850     1   
3               0.000028    5    0.3810    -9.316     1   
4               0.000002    3    0.2290   -10.096     1   
...                  ...  ...       ...       ...   ...   
170648          0.000289    7    0.0822    -3.702     1   
170649          0.000000    7    0.1010    -6.020     1   
170650          0.000009    4    0.2580    -2.226     0   
170651          0.000008    2    0.6430    -7.161     1   
170652          0.004710    7    0.1820    -4.928     1   

                                                     name  popularity  \
0       Piano Concerto No. 3 in D Minor, Op. 30: III. ...           4   
1                                 Clancy Lowered the Boom           5   
2                                               Gati Bali           5   
3                                               Danny Boy           3   
4                             When Irish Eyes Are Smiling           2   
...                                                   ...         ...   
170648                                              China          72   
170649                        Halloweenie III: Seven Days          68   
170650                                                AYA          76   
170651                                           Darkness          70   
170652                    Billetes Azules (with J Balvin)          74   

       release_date  speechiness    tempo  
0              1921       0.0366   80.954  
1              1921       0.4150   60.936  
2              1921       0.0339  110.339  
3              1921       0.0354  100.109  
4              1921       0.0380  101.665  
...    

#**Data Checking**

In [11]:
#Check the empty values
df.isnull()
df.isnull().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

In [12]:
#boolen output
df.isnull().any()

valence             False
year                False
acousticness        False
artists             False
danceability        False
duration_ms         False
energy              False
explicit            False
id                  False
instrumentalness    False
key                 False
liveness            False
loudness            False
mode                False
name                False
popularity          False
release_date        False
speechiness         False
tempo               False
dtype: bool

# **Data Handling**

In [13]:
missing_value =["N/A","na",np.nan]
df = pd.read_csv("/content/drive/MyDrive/SpotifyDataset/TrainData/data.csv", na_values=missing_value)
df.isnull().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

#**Data Visualization**

In [ ]:
sns.heatmap(df.isnull(),yticklabels=False, annot=True)

# **Data Filtering**

In [14]:
#The dropna() method removes the rows that contains NULL values.
#The dropna() method returns a new DataFrame object unless the inplace parameter is set to True, in that case the dropna() method does the removing in the original DataFrame instead
df.dropna(inplace=True)

In [15]:
df.duplicated().sum()
#if there is a duplication values
#and want to remove
df=df.drop_duplicates()

# **Data Analysis**

In [16]:
# display the first 4 rows
df.head()

valence  year  acousticness  \
0   0.0594  1921         0.982   
1   0.9630  1921         0.732   
2   0.0394  1921         0.961   
3   0.1650  1921         0.967   
4   0.2530  1921         0.957   

                                             artists  danceability  \
0  ['Sergei Rachmaninoff', 'James Levine', 'Berli...         0.279   
1                                     ['Dennis Day']         0.819   
2  ['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...         0.328   
3                                   ['Frank Parker']         0.275   
4                                     ['Phil Regan']         0.418   

   duration_ms  energy  explicit                      id  instrumentalness  \
0       831667   0.211         0  4BJqT0PrAfrxzMOxytFOIz          0.878000   
1       180533   0.341         0  7xPhfUan2yNtyFG0cUWkt8          0.000000   
2       500062   0.166         0  1o6I8BglA6ylDMrIELygv1          0.913000   
3       210000   0.309         0  3ftBPsC5vPBKxYSee08FDH          0.000028   
4       166693   0.193         0  4d6HGyGT8e121BsdKmw9v6          0.000002   

   key  liveness  loudness  mode  \
0   10     0.665   -20.096     1   
1    7     0.160   -12.441     1   
2    3     0.101   -14.850     1   
3    5     0.381    -9.316     1   
4    3     0.229   -10.096     1   

                                                name  popularity release_date  \
0  Piano Concerto No. 3 in D Minor, Op. 30: III. ...           4         1921   
1                            Clancy Lowered the Boom           5         1921   
2                                          Gati Bali           5         1921   
3                                          Danny Boy           3         1921   
4                        When Irish Eyes Are Smiling           2         1921   

   speechiness    tempo  
0       0.0366   80.954  
1       0.4150   60.936  
2       0.0339  110.339  
3       0.0354  100.109  
4       0.0380  101.665

In [17]:
#Shape of the current data frame shape (row,column)
df.shape

(170653, 19)

In [18]:
#read and display the user-rating
df=pd.read_csv(r"/content/drive/MyDrive/SpotifyDataset/TrainData/ex.csv")
df['User-Rating']

0       8.8/10
1       9.0/10
2       9.7/10
3       9.1/10
4       9.2/10
         ...  
2415    6.2/10
2416    7.2/10
2417    7.5/10
2418    6.5/10
2419    6.6/10
Name: User-Rating, Length: 2420, dtype: object

# **Deployement of Model (Model Building)**

In [19]:
# Initialize an empty list
# Iterating over a column User-Rating in a DataFrame
# For each element i in the 'User-Rating' column, you are appending a substring i[:3] to user_list
user_list=[]
for i in df['User-Rating']:
  user_list.append(i[:3])
user_list

['8.8',
 '9.0',
 '9.7',
 '9.1',
 '9.2',
 '9.1',
 '9.2',
 '9.5',
 '9.2',
 '9.6',
 '8.8',
 '8.4',
 '9.1',
 '9.2',
 '9.0',
 '9.7',
 '9.1',
 '9.0',
 '9.0',
 '9.1',
 '9.2',
 '9.2',
 '9.5',
 '8.6',
 '9.1',
 '9.0',
 '9.0',
 '9.2',
 '9.5',
 '9.4',
 '8.7',
 '9.3',
 '9.3',
 '9.5',
 '9.1',
 '9.0',
 '9.0',
 '9.1',
 '8.4',
 '8.4',
 '8.8',
 '9.2',
 '9.2',
 '9.6',
 '9.6',
 '9.0',
 '9.1',
 '8.5',
 '9.5',
 '8.5',
 '9.7',
 '8.9',
 '9.6',
 '8.5',
 '9.1',
 '8.7',
 '8.6',
 '9.3',
 '9.7',
 '8.9',
 '9.0',
 '9.0',
 '9.3',
 '9.3',
 '9.1',
 '9.0',
 '9.7',
 '9.2',
 '9.1',
 '9.0',
 '8.9',
 '9.5',
 '9.5',
 '9.7',
 '9.0',
 '8.1',
 '8.1',
 '9.5',
 '9.1',
 '8.6',
 '9.4',
 '9.0',
 '9.0',
 '9.6',
 '9.3',
 '9.0',
 '9.2',
 '9.3',
 '9.1',
 '8.6',
 '9.5',
 '9.5',
 '9.0',
 '9.4',
 '9.2',
 '9.6',
 '9.3',
 '7.7',
 '9.2',
 '9.3',
 '7.7',
 '9.0',
 '9.5',
 '9.4',
 '9.0',
 '9.2',
 '9.0',
 '9.4',
 '9.4',
 '9.1',
 '9.3',
 '9.2',
 '9.1',
 '9.0',
 '9.8',
 '8.9',
 '6.8',
 '8.9',
 '8.2',
 '8.7',
 '8.2',
 '9.4',
 '9.0',
 '8.9',
 '9.9',


In [20]:
df['User-Rating']=user_list
df

Song-Name  \
0                            Aankh Marey   
1                              Coca Cola   
2                       Apna Time Aayega   
3                                 Mungda   
4                               Tere Bin   
...                                  ...   
2415              Jana Tumhare Pyar Mein   
2416             Tum Jaise Bigde Babu Se   
2417              O Yaad Nahi Bhool Gaya   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi   

                                        Singer/Artists  \
0                  Kumar Sanu, Mika Singh, Neha Kakkar   
1                             Neha Kakkar, Tony Kakkar   
2                                        Ranveer Singh   
3                Jyotica Tangri, Shaan, Subhro Ganguly   
4     Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi   
...                                                ...   
2415                                            Mukesh   
2416                                   Lata Mangeshkar   
2417                    Lata Mangeshkar, Suresh Wadkar   
2418                                       Jagjit Kaur   
2419                                       Asha Bhosle   

                       Genre                Album/Movie User-Rating  
0             BollywoodDance                     Simmba         8.8  
1     BollywoodDanceRomantic                Luka Chuppi         9.0  
2             BollywoodDance                  Gully Boy         9.7  
3             BollywoodDance              Total Dhamaal         9.1  
4          BollywoodRomantic                     Simmba         9.2  
...                      ...                        ...         ...  
2415          BollywoodDance                    Sasural         6.2  
2416          BollywoodDance  Jab Pyar Kisi Se Hota Hai         7.2  
2417          BollywoodDance                      Lamhe         7.5  
2418          BollywoodDance          Shola Aur Shabnam         6.5  
2419          BollywoodDance          Shola Aur Shabnam         6.6  

[2420 rows x 5 columns]

In [21]:
#presenting the data in good way
df['Album/Movie'] = df['Album/Movie'].str.replace(' ','')
df['Singer/Artists'] = df['Singer/Artists'].str.replace(' ','')
df

Song-Name  \
0                            Aankh Marey   
1                              Coca Cola   
2                       Apna Time Aayega   
3                                 Mungda   
4                               Tere Bin   
...                                  ...   
2415              Jana Tumhare Pyar Mein   
2416             Tum Jaise Bigde Babu Se   
2417              O Yaad Nahi Bhool Gaya   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi   

                                 Singer/Artists                   Genre  \
0                KumarSanu,MikaSingh,NehaKakkar          BollywoodDance   
1                         NehaKakkar,TonyKakkar  BollywoodDanceRomantic   
2                                  RanveerSingh          BollywoodDance   
3             JyoticaTangri,Shaan,SubhroGanguly          BollywoodDance   
4     AseesKaur,RahatFatehAliKhan,TanishkBagchi       BollywoodRomantic   
...                                         ...                     ...   
2415                                     Mukesh          BollywoodDance   
2416                             LataMangeshkar          BollywoodDance   
2417                LataMangeshkar,SureshWadkar          BollywoodDance   
2418                                 JagjitKaur          BollywoodDance   
2419                                 AshaBhosle          BollywoodDance   

               Album/Movie User-Rating  
0                   Simmba         8.8  
1               LukaChuppi         9.0  
2                 GullyBoy         9.7  
3             TotalDhamaal         9.1  
4                   Simmba         9.2  
...                    ...         ...  
2415               Sasural         6.2  
2416  JabPyarKisiSeHotaHai         7.2  
2417                 Lamhe         7.5  
2418       SholaAurShabnam         6.5  
2419       SholaAurShabnam         6.6  

[2420 rows x 5 columns]

In [22]:
#put all rows in one variable as i can loop over it
df['tags']=df['Singer/Artists']+' '+df['Genre']+' '+df['Album/Movie']+' '+df['User-Rating']
df['tags'][0]

'KumarSanu,MikaSingh,NehaKakkar BollywoodDance Simmba 8.8'

# **Data Preparation**

In [23]:
new_df=df[['Song-Name','tags']]
new_df

Song-Name  \
0                            Aankh Marey   
1                              Coca Cola   
2                       Apna Time Aayega   
3                                 Mungda   
4                               Tere Bin   
...                                  ...   
2415              Jana Tumhare Pyar Mein   
2416             Tum Jaise Bigde Babu Se   
2417              O Yaad Nahi Bhool Gaya   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi   

                                                   tags  
0     KumarSanu,MikaSingh,NehaKakkar BollywoodDance ...  
1     NehaKakkar,TonyKakkar BollywoodDanceRomantic L...  
2              RanveerSingh BollywoodDance GullyBoy 9.7  
3     JyoticaTangri,Shaan,SubhroGanguly BollywoodDan...  
4     AseesKaur,RahatFatehAliKhan,TanishkBagchi Boll...  
...                                                 ...  
2415                  Mukesh BollywoodDance Sasural 6.2  
2416  LataMangeshkar BollywoodDance JabPyarKisiSeHot...  
2417  LataMangeshkar,SureshWadkar BollywoodDance Lam...  
2418      JagjitKaur BollywoodDance SholaAurShabnam 6.5  
2419      AshaBhosle BollywoodDance SholaAurShabnam 6.6  

[2420 rows x 2 columns]

In [24]:
new_df['tags'] = new_df['tags'].astype(str)
new_df['tags']= new_df['tags'].apply(lambda x:x.lower())
new_df

<ipython-input-24-ddd01242f3bc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].astype(str)
<ipython-input-24-ddd01242f3bc>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:x.lower())


Song-Name  \
0                            Aankh Marey   
1                              Coca Cola   
2                       Apna Time Aayega   
3                                 Mungda   
4                               Tere Bin   
...                                  ...   
2415              Jana Tumhare Pyar Mein   
2416             Tum Jaise Bigde Babu Se   
2417              O Yaad Nahi Bhool Gaya   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi   

                                                   tags  
0     kumarsanu,mikasingh,nehakakkar bollywooddance ...  
1     nehakakkar,tonykakkar bollywooddanceromantic l...  
2              ranveersingh bollywooddance gullyboy 9.7  
3     jyoticatangri,shaan,subhroganguly bollywooddan...  
4     aseeskaur,rahatfatehalikhan,tanishkbagchi boll...  
...                                                 ...  
2415                  mukesh bollywooddance sasural 6.2  
2416  latamangeshkar bollywooddance jabpyarkisisehot...  
2417  latamangeshkar,sureshwadkar bollywooddance lam...  
2418      jagjitkaur bollywooddance sholaaurshabnam 6.5  
2419      ashabhosle bollywooddance sholaaurshabnam 6.6  

[2420 rows x 2 columns]

# **Importing the CountVectorizer**

In [25]:
#Utilities to extract features from text data.
#Converts text data into a "bag of words" representation. In this representation, the text is transformed into a matrix where each row corresponds to a document and each column corresponds to a word (or token). The value in each cell represents the count of the word in the corresponding document.
#plotting confusion metrics
from sklearn.feature_extraction.text import CountVectorizer
#Create an instance of CountVectorizer with max_features=2000
#Reducing the dimensionality of the feature space
cv=CountVectorizer(max_features=2000)

# **Fitting and Transforming the Data**

In [26]:
#Learns the vocabulary from the text data in the tags column and then transforms the text data into a document-term matrix a sparse matrix where each row corresponds to a document and each column corresponds to a term from the vocabulary, with the values representing term frequencies
vectors = cv.fit_transform(new_df['tags']).toarray()

In [27]:
#There are 2420 documents and 1698 unique terms (features) in the resulting matrix
vectors.shape

(2420, 1698)

In [28]:
!pip install --upgrade scikit-learn
feature_names = cv.get_feature_names_out()

In [29]:
# Ensure that the cell defining `similarity` is executed first
!pip install scikit-learn==1.1.3
!pip install --upgrade scikit-learn
from sklearn.metrics.pairwise import cosine_similarity
# Learns the vocabulary from the text data in the tags column and then transforms the text data into a document-term matrix a sparse matrix where each row corresponds to a document and each column corresponds to a term from the vocabulary, with the values representing term frequencies
vectors = cv.fit_transform(new_df['tags']).toarray()
print(vectors)
similarity = cosine_similarity(vectors)

  Using cached scikit_learn-1.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.5 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.0
    Uninstalling scikit-learn-1.5.0:
      Successfully uninstalled scikit-learn-1.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 1.6.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.1.3 which is incompatible.


  Using cached scikit_learn-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.1.3
    Uninstalling scikit-learn-1.1.3:
      Successfully uninstalled scikit-learn-1.1.3
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
similarity = cosine_similarity(vectors)
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999999),
 (5, 0.5163977794943223),
 (34, 0.5163977794943223),
 (184, 0.5163977794943223),
 (271, 0.5163977794943223),
 (375, 0.5163977794943223),
 (469, 0.5163977794943223),
 (544, 0.5163977794943223),
 (591, 0.5163977794943223),
 (610, 0.5163977794943223),
 (825, 0.5163977794943223),
 (925, 0.5163977794943223),
 (1406, 0.5163977794943223),
 (1620, 0.5163977794943223),
 (1955, 0.5163977794943223),
 (2173, 0.5163977794943223),
 (2300, 0.5163977794943223),
 (2387, 0.5163977794943223),
 (11, 0.4472135954999579),
 (35, 0.4472135954999579),
 (40, 0.4472135954999579),
 (88, 0.4472135954999579),
 (115, 0.4472135954999579),
 (117, 0.4472135954999579),
 (136, 0.4472135954999579),
 (142, 0.4472135954999579),
 (242, 0.4472135954999579),
 (243, 0.4472135954999579),
 (264, 0.4472135954999579),
 (304, 0.4472135954999579),
 (311, 0.4472135954999579),
 (345, 0.4472135954999579),
 (366, 0.4472135954999579),
 (379, 0.4472135954999579),
 (390, 0.4472135954999579),
 (410, 0.44721359549995

In [31]:
new_df.rename(columns={'Song-Name':'title'},inplace=True)

<ipython-input-31-9a52c662c89c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns={'Song-Name':'title'},inplace=True)


In [32]:
def recommend(music):
    music_index=new_df[new_df['title']==music].index[0]
    distances=similarity[music_index]
    music_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in music_list:
        print(new_df.iloc[i[0]].title)

In [34]:
recommend('Proper Patola')

Abhi Toh Party Shuru Hui Hai
Bhare Bazaar
Tareefan Remix
Pant Mein Gun
Pee Paa Pee Paa


In [35]:
df.head(50)

Song-Name  \
0                       Aankh Marey   
1                         Coca Cola   
2                  Apna Time Aayega   
3                            Mungda   
4                          Tere Bin   
5                         Gali Gali   
6                     Chamma Chamma   
7                   Mere Gully Mein   
8                          Kamariya   
9   Ek Ladki Ko Dekha Toh Aisa Laga   
10                   Swag Se Swagat   
11                  Poster Lagwa Do   
12                      Daaru Wargi   
13                           Dilbar   
14                    Proper Patola   
15                            Doori   
16                 Dil Diyan Gallan   
17                     Husn Parcham   
18                  Bom Diggy Diggy   
19                       Issaqbaazi   
20                     Mere Naam Tu   
21    High Rated Gabru – Nawabzaade   
22                    Dekhte Dekhte   
23                          Zingaat   
24                         Tareefan   
25            Mile Ho Tum (Reprise)   
26                        Dil Chori   
27                 Tere Naal Nachna   
28                 Dil Meri Na Sune   
29               Dhadak Title Track   
30                          Heeriye   
31                          Chogada   
32              Gud Naal Ishq Mitha   
33                       Paniyon Sa   
34                    Milegi Milegi   
35                      Morni Banke   
36                     Bhare Bazaar   
37                        Khalibali   
38              Aao Kabhi Haveli Pe   
39                Badri Ki Dulhania   
40                       Cheez Badi   
41                          Dholida   
42                       Sweetheart   
43                        Namo Namo   
44                        Qaafirana   
45                         Tu Hi Re   
46                Chhote Chhote Peg   
47                 Galti Se Mistake   
48                    Phir Mulaaqat   
49                     Kala Chashma   

                                     Singer/Artists                   Genre  \
0                    KumarSanu,MikaSingh,NehaKakkar          BollywoodDance   
1                             NehaKakkar,TonyKakkar  BollywoodDanceRomantic   
2                                      RanveerSingh          BollywoodDance   
3                 JyoticaTangri,Shaan,SubhroGanguly          BollywoodDance   
4         AseesKaur,RahatFatehAliKhan,TanishkBagchi       BollywoodRomantic   
5                                        NehaKakkar          BollywoodDance   
6                         Arun,Ikka,NehaKakkar,Romy          BollywoodDance   
7                                      RanveerSingh          BollywoodDance   
8                                      DarshanRaval          BollywoodDance   
9                          DarshanRaval,RochakKohli       BollywoodRomantic   
10                         NehaBhasin,VishalDadlani          BollywoodDance   
11                          MikaSingh,SunandaSharma          BollywoodDance   
12                                     GuruRandhawa          BollywoodDance   
13                 DhvaniBhanushali,Ikka,NehaKakkar          BollywoodDance   
14                 AasthaGill,Badshah,DiljitDosanjh          BollywoodDance   
15                                     RanveerSingh          BollywoodDance   
16                                        AtifAslam       BollywoodRomantic   
17                         BhoomiTrivedi,RajaKumari          BollywoodDance   
18                           JasminWalia,ZackKnight          BollywoodDance   
19                       DivyaKumar,SukhwinderSingh          BollywoodDance   
20                                  AbhayJodhpurkar       BollywoodRomantic   
21                                     GuruRandhawa          BollywoodDance   
22                                        AtifAslam       BollywoodRomantic   
23                                        Ajay,Atul          BollywoodDance   
24                                          Badshah          

In [39]:
import pickle
pickle.dump(new_df,open('musicrec.pkl','wb'))

In [38]:
pickle.dump(similarity,open('similarities.pkl','wb'))